### ISSUE TITLE
ycf1 gene not available in the ontology

### ISSUE THREAD

**Issue by dreyes17** [kushidat/IOBC#1]
Hello,

I am currently working on a DNA barcoding project. I have noticed that your ontology covers some of our needs due to its very good classification of genes. Unfortunately it doesn't have one of the most important **chloroplast gene** for DNA Barcoding the **ycf1**. It could be very easy to insert because it is at the same level of matK gene or rbcL gene.

Thank you very much.

**Comment by kushidat** [comment]
Hi Daniel,

Thank you so much for suggesting ycf1 gene addition.
I have updated the IOBC in Github and BioPortal. 
Please check it, and if any questions and comments, let me know.

http://purl.jp/bio/4/id/2021000

https://github.com/kushidat/IOBC
http://purl.bioontology.org/ontology/IOBC

Best regards,
Tatsuya.

-- 
Tatsuya Kushida, Ph.D.
Integrated Bioresource Information Division,
RIKEN BioResource Research Center
3-1-1 koyadai, Tsukuba, Ibaraki 305-0074, JAPAN
TEL: +81 29 836 9178 FAX: +81 29 836 9337
mob: +81 90 6199 2657
tatsuya.kushida@riken.jp
https://orcid.org/0000-0002-0784-4113
https://brc.riken.jp/

**Comment by dreyes17** [comment]
Thank you very much to you for the ontology and the fast solution.
